export const allCategories: string[] = [
  "Fresh Produce",
  "Organic Fruits",
  "Organic Vegetables",
  "Conventional Fruits",
  "Conventional Vegetables",
  "Dairy and Alternatives",
  "Milk Products",
  "Plant-Based Dairy",
  "Bakery and Breakfast",
  "Bread",
  "Cereals",
  "Pastries",
  "Meats and Seafood",
  "Poultry",
  "Red Meat",
  "Seafood",
  "Frozen Goods",
  "Frozen Meals",
  "Frozen Desserts",
  "Frozen Vegetables",
  "Pantry",
  "Canned Goods",
  "Spices and Seasonings",
  "Snacks",
  "Beverages",
  "Alcoholic Beverages",
  "Non-Alcoholic Beverages",
  "Coffees and Teas",
  "Health and Wellness",
  "Supplements",
  "Organic and Natural Products",
  "Household and Cleaning",
  "Cleaners",
  "Tools and Supplies",
  "Pet Supplies",
  "Dogs",
  "Cats",
  "Other Pets",
  "Gourmet Foods",
  "International Foods",
  "Specialty Cheeses",
  "Organic Snacks",
  "Gardening Supplies",
  "Plants",
  "Gardening Tools",
  "Soil and Fertilizers",
  "Personal Care",
  "Skincare",
  "Haircare",
  "Oral Care",
];
