const categories = [
  "Fresh Produce",
  "Sweets",
  "Chocolate",
  "Jam",
  "Shampoo",
  "Fruits",
  "Vegetables",
  "Herbs",
  "Meat and Seafood",
  "Beef",
  "Chicken",
  "Pork",
  "Fish",
  "Shellfish",
  "Dairy and Eggs",
  "Milk",
  "Cheese",
  "Yogurt",
  "Eggs",
  "Butter",
  "Bakery",
  "Bread",
  "Pastries",
  "Cakes",
  "Cookies",
  "Pies",
  "Frozen Foods",
  "Frozen Vegetables",
  "Frozen Pizza",
  "Ice Cream",
  "Frozen Meals",
  "Frozen Desserts",
  "Pantry Staples",
  "Rice",
  "Pasta",
  "Canned Goods",
  "Condiments",
  "Spices",
  "Beverages",
  "Water",
  "Juice",
  "Soda",
  "Coffee",
  "Tea",
  "Snacks",
  "Chips",
  "Crackers",
  "Nuts",
  "Popcorn",
  "Granola Bars",
  "Breakfast and Cereal",
  "Cereal",
  "Oatmeal",
  "Pancake Mix",
  "Syrup",
  "Breakfast Bars",
  "Household Essentials",
  "Cleaning Supplies",
  "Paper Products",
  "Laundry",
  "Pet Supplies",
  "Baby and Childcare",
  "Diapers",
  "Baby Food",
  "Formula",
  "Baby Care Products",
  "Toys",
  "Health and Wellness",
  "Vitamins",
  "Supplements",
  "First Aid",
  "Personal Care",
  "Over-the-Counter Medicines",
  "International Foods",
  "Asian",
  "Mexican",
  "Italian",
  "Indian",
  "Middle Eastern",
  "Organic and Natural",
  "Organic Fruits and Vegetables",
  "Natural Snacks",
  "Organic Dairy",
  "Natural Cleaning Products",
  "Special Dietary Needs",
  "Gluten-Free",
  "Vegan",
  "Kosher",
  "Sugar-Free",
  "Nut-Free",
  "Alcoholic Beverages (where applicable)",
  "Beer",
  "Wine",
  "Spirits",
  "Mixers",
  "Non-Alcoholic Drinks",
];

export default categories;
